### ISSUE TITLE
How to generate an ETag from an object?

### ISSUE THREAD

**Issue by toymachiner62** [jshttp/etag#28]
@dougwilson helped me in this issue https://github.com/expressjs/express/issues/3947 with understanding how express generates ETag's. He said that the ETag is generated from the response body but how do you actually generate an ETag from a JSON object?

This simple test

```js
'use strict'
const etag = require('etag')
const document = {}
const value = etag(document)
console.log('value = ', value)
```
Gives the error:
```
TypeError: argument entity must be string, Buffer, or fs.Stats
    at etag (/Users/tomcaflisch/Sites/ciitizen/ciitizen-profile-service/node_modules/etag/index.js:83:11)
    at Object.<anonymous> (/Users/tomcaflisch/Sites/ciitizen/ciitizen-profile-service/test.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by dougwilson** [comment]
Serialize it with like `JSON.stringify`

**Comment by toymachiner62** [comment]
Is there a reason that this `etag` lib doesn't do that automatically when objects are passed in?

**Comment by dougwilson** [comment]
Well, it wouldn't know if you'll then serialize it the same way when actually sending it to the client.

**Comment by toymachiner62** [comment]
But what's the difference between passing in a string to `etag()` and an object? In either case I just want whatever I pass in to generate an ETag.

It seems like discrimination against objects right now.

**Comment by dougwilson** [comment]
Well, this is just the interface I choose to provide for my module. You can always make a new module that has the interface you like.

**Comment by toymachiner62** [comment]
That's fair. Would you accept a PR to automatically serialize objects and generate an etag?

**Comment by dougwilson** [comment]
No
